
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: foxnews_development


test:
  <<: *default
  database: foxnews_test